apiVersion: v1
kind: Service
metadata:
  name: mail
spec:
  selector:
    app: mail
  ports:
  - name: smtp
    protocol: TCP
    port: 25
    targetPort: 25

  - name: alt-smtp
    protocol: TCP
    port: 143
    targetPort: 143

  - name: ssl-smtp
    protocol: TCP
    port: 993
    targetPort: 993
